version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: sqlite:3.39
    volumes:
      - db_data:/var/lib/sqlite3
volumes:
  db_data: